"""add description field to books table

Revision ID: 3ecd43347253
Revises: 52f3ee4d8d8d
Create Date: 2025-05-30 07:12:52.649255

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ecd43347253"
down_revision: Union[str, None] = "52f3ee4d8d8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("description", sa.String(), nullable=True))

    # заполняем поле для уже существующих записей
    op.execute("UPDATE books SET description = 'No description'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "description")
    # ### end Alembic commands ###
